// js/katalog.js

const MANIS = [
  { id:1, name:'Cheese Crunchy', price:'Rp 10.000', priceN:10000, img:'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80', badge:'', cat:'Roti Manis', category: 'manis', desc:'Varian Cheese Crunchy spesial dari Rokkus...', tags:['Cheese Crunchy'], stok: 50 },
  { id:2, name:'Lotus Biscoff', price:'Rp 16.000', priceN:16000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277014/Lotus_Biscoff_w9k9x1.png', badge:'new', badgeLabel:'New ★', cat:'Roti Manis', category: 'manis', desc:'Isian Lotus Biscoff premium yang creamy dengan cita rasa karamel khas.', tags:['Lotus Biscoff', 'Premium'], stok: 50 },
  { id:3, name:'Coklat Keju', price:'Rp 13.000', priceN:13000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277015/Coklat_Keju_hwsjmm.png', badge:'hot', badgeLabel:'Best Seller 👍', cat:'Roti Manis', category: 'manis', desc:'Paduan sempurna isian coklat lumer dengan taburan keju cheddar gurih.', tags:['Coklat Keju'], stok: 50 },
  { id:4, name:'Coklat Kacang', price:'Rp 15.000', priceN:15000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277020/Coklat_Kacang_ab6kbe.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Kombinasi coklat premium dengan kacang yang renyah.', tags:['Coklat Kacang'], stok: 50 },
  { id:5, name:'Coklat Mozarella', price:'Rp 15.000', priceN:15000, img:'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80', badge:'', cat:'Roti Manis', category: 'manis', desc:'Coklat dengan lelehan keju mozarella spesial dari Rokkus...', tags:['Coklat Mozarella'], stok: 50 },
  { id:6, name:'Nutella Keju', price:'Rp 17.000', priceN:17000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277026/Nutella_Keju_uyxm87.png', badge:'hot', badgeLabel:'Best Seller 👍', cat:'Roti Manis', category: 'manis', desc:'Isian Nutella hazelnut original berpadu dengan keju parut.', tags:['Nutella Keju'], stok: 50 },
  { id:7, name:'Silverqueen Keju', price:'Rp 20.000', priceN:20000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277015/Silverqueen_z9ku6f.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Silverqueen Keju premium lezat dari Rokkus...', tags:['Silverqueen Keju'], stok: 50 },
  { id:8, name:'Ovomaltine Keju', price:'Rp 20.000', priceN:20000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277015/Ovomaltine_nevvd5.png', badge:'hot', badgeLabel:'Recommended 👍', cat:'Roti Manis', category: 'manis', desc:'Isian Ovomaltine malt yang khas dan legit dipadukan keju.', tags:['Ovomaltine Keju'], stok: 50 },
  { id:9, name:'Coklat', price:'Rp 10.000', priceN:10000, img:'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80', badge:'', cat:'Roti Manis', category: 'manis', desc:'Roti Coklat klasik dengan isian melimpah.', tags:['Coklat'], stok: 50 },
  { id:10, name:'Keju', price:'Rp 10.000', priceN:10000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277021/Keju_byipwf.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Isian keju cheddar murni yang gurih dan manis.', tags:['Keju'], stok: 50 },
  { id:11, name:'Strawberry', price:'Rp 10.000', priceN:10000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277024/Strawberry_ctacpp.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Selai strawberry yang segar membalut roti kukus lembut.', tags:['Strawberry'], stok: 50 },
  { id:12, name:'Blueberry', price:'Rp 10.000', priceN:10000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277022/Bluberry_uyf8zt.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Isian selai bluberry dengan rasa manis segar khas buah biru.', tags:['Blueberry'], stok: 50 },
  { id:13, name:'Tiramisu', price:'Rp 10.000', priceN:10000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277015/Tiramisu_Crunchy_gbyq50.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Terinspirasi dari dessert Italia klasik. Perpaduan rasa kopi dan coklat.', tags:['Tiramisu'], stok: 50 },
  { id:14, name:'Greentea', price:'Rp 10.000', priceN:10000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277022/Green_Tea_Crunchy_tlip83.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Isian greentea matcha premium yang punya rasa pahit manis khas.', tags:['Greentea'], stok: 50 },
  { id:15, name:'Kacang', price:'Rp 12.000', priceN:12000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277030/Kacang_Peanut_Butter_w0kin1.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Peanut butter creamy yang gurih dan sedikit manis.', tags:['Kacang'], stok: 50 },
  { id:16, name:'Nutella', price:'Rp 14.000', priceN:14000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277026/Nutella_ulvynz.png', badge:'hot', badgeLabel:'Best Seller 👍', cat:'Roti Manis', category: 'manis', desc:'Isian Nutella hazelnut original yang melimpah tanpa campuran.', tags:['Nutella'], stok: 50 },
  { id:17, name:'Silverqueen', price:'Rp 17.000', priceN:17000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277015/Silverqueen_z9ku6f.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Coklat Silverqueen premium spesial dari Rokkus...', tags:['Silverqueen'], stok: 50 },
  { id:18, name:'Ovomaltine', price:'Rp 17.000', priceN:17000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277015/Ovomaltine_nevvd5.png', badge:'', cat:'Roti Manis', category: 'manis', desc:'Isian Ovomaltine original yang malty, legit, dan kaya rasa.', tags:['Ovomaltine'], stok: 50 }
];

const ASIN = [
  { id:19, name:'Telur Mayo', price:'Rp 10.000', priceN:10000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277089/Telor_Mayo_w7pv09.png', badge:'hot', badgeLabel:'Recommended 👍', cat:'Roti Asin', category: 'asin', desc:'Isian telur dengan mayo creamy yang gurih dan lembut.', tags:['Telur Mayo'], stok: 50 },
  { id:20, name:'Sosis Mayo', price:'Rp 12.000', priceN:12000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277090/Sosis_Mayo_fs1sw6.png', badge:'', cat:'Roti Asin', category: 'asin', desc:'Sosis juicy yang gurih dipadukan mayo lembut.', tags:['Sosis Mayo'], stok: 50 },
  { id:21, name:'Telur Sosis Mayo', price:'Rp 13.000', priceN:13000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277095/Telor_Sosis_psh3fb.png', badge:'', cat:'Roti Asin', category: 'asin', desc:'Kombinasi telur + sosis + mayo dalam satu roti.', tags:['Telur Sosis Mayo'], stok: 50 },
  { id:22, name:'Beef Mayo', price:'Rp 14.000', priceN:14000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277092/Beef_Mayo_lkkych.png', badge:'hot', badgeLabel:'Best Seller 👍', cat:'Roti Asin', category: 'asin', desc:'Daging beef berbumbu yang juicy dipadukan mayo creamy.', tags:['Beef Mayo'], stok: 50 },
  { id:23, name:'Beef Sosis Mayo', price:'Rp 16.000', priceN:16000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277088/Beef_Sosis_Mayo_oropgt.png', badge:'', cat:'Roti Asin', category: 'asin', desc:'Gabungan beef berbumbu dan sosis dengan mayo.', tags:['Beef Sosis Mayo'], stok: 50 },
  { id:24, name:'Double Beef', price:'Rp 18.000', priceN:18000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277088/Double_Beef_qpxoh4.png', badge:'hot', badgeLabel:'Best Seller 👍', cat:'Roti Asin', category: 'asin', desc:'Dobel porsi daging beef berbumbu untuk kamu yang mau kenyang.', tags:['Double Beef'], stok: 50 },
  { id:25, name:'Telur Beef Sosis', price:'Rp 18.000', priceN:18000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277085/Telor_Beef_Sosis_wnbhei.png', badge:'hot', badgeLabel:'Best Seller 👍', cat:'Roti Asin', category: 'asin', desc:'Kombo paling lengkap: telur + beef + sosis dalam satu roti.', tags:['Telur Beef Sosis'], stok: 50 },
  { id:26, name:'Beef Mozarella', price:'Rp 19.000', priceN:19000, img:'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80', badge:'', cat:'Roti Asin', category: 'asin', desc:'Daging beef berbumbu ditambah keju mozarella meleleh.', tags:['Beef Mozarella'], stok: 50 },
  { id:27, name:'Telur Beef Mozarella', price:'Rp 22.000', priceN:22000, img:'https://res.cloudinary.com/dxyhpvjiv/image/upload/v1779277086/Telor_Beef_mycgxw.png', badge:'', cat:'Roti Asin', category: 'asin', desc:'Telur, beef, dan balutan mozarella lezat.', tags:['Telur Beef Mozarella'], stok: 50 }
];

const TAMBAHAN = [
  { id:28, name:'Keju Parut/Slice', price:'Rp 3.000', priceN:3000, img:'https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80', badge:'', cat:'Tambahan', category: 'tambahan', desc:'Tambahan Ekstra Keju.', tags:['Keju'], stok: 50 },
  { id:29, name:'Telur', price:'Rp 3.000', priceN:3000, img:'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80', badge:'', cat:'Tambahan', category: 'tambahan', desc:'Tambahan Ekstra Telur.', tags:['Telur'], stok: 50 },
  { id:30, name:'Selai Lain', price:'Rp 3.000', priceN:3000, img:'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=600&q=80', badge:'', cat:'Tambahan', category: 'tambahan', desc:'Tambahan Selai.', tags:['Selai Lain'], stok: 50 },
  { id:31, name:'Mozarella', price:'Rp 5.000', priceN:5000, img:'https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80', badge:'', cat:'Tambahan', category: 'tambahan', desc:'Tambahan Ekstra Mozarella.', tags:['Mozarella'], stok: 50 }
];

// Array gabungan untuk digunakan oleh aplikasi 
const products = [...MANIS, ...ASIN, ...TAMBAHAN];
const ALL_PRODUCTS = products;